<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<!--Avalonia doesen't support TrimMode=link currently,but we are working on that https://github.com/AvaloniaUI/Avalonia/issues/6892 -->
		<TrimMode>copyused</TrimMode>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
	</PropertyGroup>
	<ItemGroup>
		<Folder Include="Models\" />
		<AvaloniaResource Include="Assets\**" />
		<None Remove=".gitignore" />
	</ItemGroup>
	<ItemGroup>
		<TrimmableAssembly Include="Avalonia.Themes.Fluent" />
		<TrimmableAssembly Include="Avalonia.Themes.Default" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Autofac" Version="9.0.0" />
		<PackageReference Include="Avalonia" Version="11.3.11" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.11" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
		<PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
		<PackageReference Include="Splat.Autofac" Version="17.2.1" />
	</ItemGroup>
</Project>